application: arts-612
version: xo-responsive
runtime: python27
api_version: 1
threadsafe: yes

# index files
handlers:

# site root
- url: /static
  static_dir: static
  secure: optional

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/themes/v0/favicon.ico
  upload: static/themes/v0/favicon\.ico

- url: .*
  static_files: www/index.html
  upload: www/index.html
