application: arts-612
version: phase-2-20141217
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
 
# index files
handlers:

- url: /beta.*
  script: main.app
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/themes/v0/favicon.ico
  upload: static/themes/v0/favicon\.ico

# Route Everything else to the main public webapp
- url: .*
  script: main.app