application: arts-612

version: master-new-client

runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

#
#  handlers:
#  - url: /api.*
#    script: main.app
#
#  - url: /import.*
#    script: main.app
#
#  - url: /static
#    static_dir: static
#    secure: optional
#
#  - url: .*
#    script: main.app

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (\.DS_Store)|
 (node_modules/.*)|

 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (.*\.svn/.*)||
 (.*\.swp)||
 (^submodules.txt)|
 (^\.gitignore)|
 (^\.coverage)|
 (^\.Makefile)|
 (^\nosetests\.xml)|
 (^\requirements\.txt)|
 (^\requirements_dev\.txt)|
 (\.modules-cache/.*)|
 (\.modules-cache/.*)|
 (.*manifest/.*)||
 (^datastore/.*)|
 (^flex/.*)|
 (^antennae/.*)|
 (^data/.*)|
 (^logs/.*)|
 
 (^external/Crypto/.*)|
 (^external/coverage/.*)|
 (^external/django/.*)|
 (^external/linkenv/.*)|
 (^external/mock\.py)|
 (^external/nose/.*)|
 (^external/nose_exclude\.py)|
 (^external/nosegae\.py)|
 (^external/termstyle\.py)|
 (^external/PIL/.*)|
 (^external/yanc/.*)|
 
 
 (^.externalToolBuilders/.*)|
 (^web/test/wf-test-documents/.*)|
 (^static/test/wf-test-documents/.*)|
 (^test-reports/.*)|
 (^web/bootstrap/.*)|
 (^static/bootstrap/docs/.*)|
 (.git/.*)|
 (.module-cache/.*)|
 (.*/node_modules/.*)|

 (.*SpecRunner.html)|
 (.*\.graffle)|
 (.*\.less)|
 (.*\.scss)|
 (.*\.md)|
 (^web/js/angular/.*)|
 (^web/js/jasmine/.*)|
 (^web/js/testscular/.*)|
 (^web/js/require/.*)|
 (^web/js/sugar/.*)|
 (^web/js/hammer/.*)|
 (^web/js/handlebars/.*)|
 (^documents/tests/.*)|
 (^apps/viewer/tests/.*)|
 (^apps/rv/tools/build/\.sass-cache/.*)|
 (^docs/.*)|
 (^cover/.*)|
 (^apps/certifier/tests/.*)|
 (^apps/home/assets/.*)|
 (^apps/home/node_modules/.*)|
 (^apps/documentservices/node_modules/.*)|
 (^apps/canary/.*\.(?!py$|pyc$))|
 (^external_libs/richapps/build/.*)|
 (^static/web-skin/?.*/img/icons)|
 (^static/web-skin/?.*/img/splash/android/.*)|
 (^static/web-skin/?.*/ico/android/.*)|
 (^static/web-skin/?.*/ico/beta/.*)|
 (^static/web-skin/?.*/ico/.*precomposed.*)|
 (\.bower-cache/.*)|
 (\.bower-registry/.*)|
 (\.grunt/.*)|
 (^python-scripts/.*)|
 (^external_libs/sky/docviewer/assets/.*)|
 (^external_libs/wf/apps/books/assets/.*)|
 (^external_libs/wf/apps/dc/dashboard/assets/.*)|
 (^external_libs/wf/apps/section16/assets/.*)|
 )$

# index files
handlers:


- url: /app.*
  static_files: public/app.html
  upload: public/app\.html
  login: admin

# Node modules that are for client
- url: /node_modules
  static_dir: node_modules
  secure: optional

- url: /public
  static_dir: public
  secure: optional

- url: /beta.*
  script: main.app
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /api.*
  script: rest.main.app
  secure: optional

- url: /admin.*
  static_files: static/admin/app.html
  upload: static/admin/app\.html
  login: admin

- url: /import.*
  script: import.main.app
  secure: optional

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/themes/v0/favicon.ico
  upload: static/themes/v0/favicon\.ico

# Route Everything else to the main public webapp
- url: .*
  script: main.app
