application: arts-612
version: angular

runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

#
#  handlers:
#  - url: /api.*
#    script: main.app
#
#  - url: /import.*
#    script: main.app
#
#  - url: /static
#    static_dir: static
#    secure: optional
#
#  - url: .*
#    script: main.app

 
# index files
handlers:


- url: /app.*
  static_files: public/app.html
  upload: public/app\.html
  login: admin

# Node modules that are for client
- url: /node_modules
  static_dir: node_modules
  secure: optional

- url: /public
  static_dir: public
  secure: optional

- url: /beta.*
  script: main.app
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /api.*
  script: rest.main.app
  secure: optional

- url: /admin.*
  static_files: static/admin/app.html
  upload: static/admin/app\.html
  login: admin

- url: /import.*
  script: import.main.app
  secure: optional

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/themes/v0/favicon.ico
  upload: static/themes/v0/favicon\.ico

- url: .*
  script: main.app
