application: arts-612
version: betax-20150407
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
  - remote_api: on

#
#  handlers:
#  - url: /api.*
#    script: main.app
#
#  - url: /import.*
#    script: main.app
#
#  - url: /static
#    static_dir: static
#    secure: optional
#
#  - url: .*
#    script: main.app


skip_files: |
   ^(.*/)?(
   (app\.yaml)|
   (app\.yml)|
   (index\.yaml)|
   (index\.yml)|
   (#.*#)|
   (.*~)|
   (.*\.py[co])|
   (.git/.*)|
   (.gitignore)|
   (.DS_Store)|
   (^docs/.*)|
   (^static/admin/js/react/src/.*)|
   (^public/src/.*)|

   (^external/PIL/.*)| 
   (^external/nose/.*)|
   (^external/pip/.*)|
   (^'external/easy_install\.*)|
   (^external/mock\.*)| 
   (^external/nose_exclude.*)|
   (^external/nosegae.*)|
   (^external/rednose.*)| 
   (^external/yanc/.*)|
   (^external/setuptools/.*)|
   (^external/rsa/.*)|
   )$

# index files
handlers:


- url: /app.*
  static_files: public/app.html
  upload: public/app\.html
  login: admin

# Node modules that are for client
- url: /node_modules
  static_dir: node_modules
  secure: optional

- url: /public
  static_dir: public
  secure: optional

- url: /beta.*
  script: main.app
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /api.*
  script: rest.main.app
  secure: optional

- url: /admin.*
  script: admin.main.app
  secure: optional
  login: admin

#- url: /import.*
#  script: import.main.app
#  secure: optional

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/themes/v0/favicon.ico
  upload: static/themes/v0/favicon\.ico

# Route Everything else to the main public webapp
- url: .*
  script: main.app
