application: arts-612
version:  master-2016api
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
  - remote_api: on

skip_files: |
   ^(.*/)?(
   (app\.yaml)|
   (app\.yml)|
   (index\.yaml)|
   (index\.yml)|
   (#.*#)|
   (.*~)|
   (.*\.py[co])|
   (.git/.*)|
   (.gitignore)|
   (.DS_Store)|
   (^docs/.*)|
   (^static/admin/js/react/src/.*)|
   (^external/PIL/.*)|
   (^external/nose/.*)|
   (^external/pip/.*)|
   (^'external/easy_install\.*)|
   (^external/mock\.*)|
   (^external/nose_exclude.*)|
   (^external/nosegae.*)|
   (^external/rednose.*)|
   (^external/yanc/.*)|
   (^external/setuptools/.*)|
   (^external/rsa/.*)|
   )$

# index files
handlers:

- url: /static
  static_dir: static
  secure: optional

- url: /api.*
  script: rest.main.app
  secure: optional

- url: /admin.*
  script: admin.main.app
  secure: optional
  login: admin

- url: /favicon\.ico
  static_files: static/themes/v0/favicon.ico
  upload: static/themes/v0/favicon\.ico

# Route Everything else to the main public webapp
- url: .*
  script: main.app
